- ignore:
    name: "Use newtype instead of data"
- ignore:
    name: "Use section"
- ignore:
    name: "Use String"
- ignore:
    name: "Use ++"
- ignore:
    name: "Use tuple-section"
- ignore:
    name: "Use record patterns"
- ignore:
    name: "Replace case with maybe"
- ignore:
    name: "Avoid lambda"
