resolver: lts-22.22
packages:
- bevel-api
- bevel-api-gen
- bevel-api-server
- bevel-api-server-data
- bevel-api-server-data-gen
- bevel-api-server-gen
- bevel-cli
- bevel-client
- bevel-client-data
- bevel-client-data-gen
- bevel-data
- bevel-data-gen
extra-deps: 
- github: NorfairKing/opt-env-conf
  commit: dcc6dbd8af9460e267e10704301c011a95c0de84
  subdirs:
    - opt-env-conf
    - opt-env-conf-test

- github: NorfairKing/safe-coloured-text
  commit: 26b7657428f277f819a0831cbddddb7f4c5408f9
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-layout
    - safe-coloured-text-terminfo

- github: NorfairKing/autodocodec
  commit: be4aba9ef133520a8a4087aa26915aaabf1376a7
  subdirs:               
    - autodocodec  
    - autodocodec-schema  
    - autodocodec-yaml                            
    - autodocodec-nix
- github: NorfairKing/sydtest
  commit: 6be618a53366d2453ba55da6cddc119d6d589916
  subdirs:
  - sydtest
  - sydtest-aeson
  - sydtest-discover
  - sydtest-hspec
  - sydtest-persistent
  - sydtest-persistent-sqlite
  - sydtest-process
  - sydtest-servant
  - sydtest-typed-process
  - sydtest-wai
  - sydtest-yesod
- github: NorfairKing/appendful
  commit: 9100ac7fb88e8bb0357e6c648d1b5b404efcd4f8
  subdirs:
  - appendful
  - appendful-persistent
  - genvalidity-appendful
- github: NorfairKing/validity
  commit: a251897dc1eb7e851fd4d3dbc6fa976d22388f27
  subdirs:
  - validity
  - validity-aeson
  - validity-bytestring
  - validity-containers
  - validity-path
  - validity-persistent
  - validity-primitive
  - validity-scientific
  - validity-text
  - validity-time
  - validity-unordered-containers
  - validity-uuid
  - validity-vector
  - genvalidity
  - genvalidity-aeson
  - genvalidity-bytestring
  - genvalidity-containers
  - genvalidity-criterion
  - genvalidity-hspec
  - genvalidity-hspec-aeson
  - genvalidity-hspec-binary
  - genvalidity-hspec-cereal
  - genvalidity-hspec-hashable
  - genvalidity-hspec-optics
  - genvalidity-hspec-persistent
  - genvalidity-path
  - genvalidity-persistent
  - genvalidity-property
  - genvalidity-scientific
  - genvalidity-sydtest
  - genvalidity-sydtest-aeson
  - genvalidity-sydtest-hashable
  - genvalidity-sydtest-lens
  - genvalidity-sydtest-persistent
  - genvalidity-text
  - genvalidity-time
  - genvalidity-unordered-containers
  - genvalidity-uuid
  - genvalidity-vector

ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef

system-ghc: true
nix:
  enable: false
with-hpack: hpack
