resolver: lts-19.6
packages:
- bevel-api
- bevel-api-gen
- bevel-api-server
- bevel-api-server-data
- bevel-api-server-data-gen
- bevel-api-server-gen
- bevel-cli
- bevel-client
- bevel-client-data
- bevel-client-data-gen
- bevel-data
- bevel-data-gen
extra-deps:
- github: NorfairKing/autodocodec
  commit: 867633a84a7f34df6559ad24590cf67523d1c956
  subdirs:
  - autodocodec
  - autodocodec-schema
  - autodocodec-yaml
- github: NorfairKing/safe-coloured-text
  commit: 7273b03930261d1f49b842f673fded3e6f31da24
  subdirs:
  - safe-coloured-text
  - safe-coloured-text-layout
  - safe-coloured-text-terminfo
- github: NorfairKing/sydtest
  commit: 1fde94931f506c412d04c3df12ee6cc655682729
  subdirs:
  - sydtest
  - sydtest-aeson
  - sydtest-discover
  - sydtest-hspec
  - sydtest-persistent
  - sydtest-persistent-sqlite
  - sydtest-process
  - sydtest-servant
  - sydtest-typed-process
  - sydtest-wai
  - sydtest-yesod
- github: NorfairKing/appendful
  commit: fcaea3b910bdab241a8c47d2c56b3681df1e32f7
  subdirs:
  - appendful
  - appendful-persistent
  - genvalidity-appendful
- github: NorfairKing/validity
  commit: 0cfa408d214f21488c28f280851704fd96756b34
  subdirs:
  - validity
  - validity-aeson
  - validity-bytestring
  - validity-containers
  - validity-path
  - validity-persistent
  - validity-primitive
  - validity-scientific
  - validity-text
  - validity-time
  - validity-unordered-containers
  - validity-uuid
  - validity-vector
  - genvalidity
  - genvalidity-aeson
  - genvalidity-bytestring
  - genvalidity-containers
  - genvalidity-criterion
  - genvalidity-hspec
  - genvalidity-hspec-aeson
  - genvalidity-hspec-binary
  - genvalidity-hspec-cereal
  - genvalidity-hspec-hashable
  - genvalidity-hspec-optics
  - genvalidity-hspec-persistent
  - genvalidity-path
  - genvalidity-persistent
  - genvalidity-property
  - genvalidity-scientific
  - genvalidity-sydtest
  - genvalidity-sydtest-aeson
  - genvalidity-sydtest-hashable
  - genvalidity-sydtest-lens
  - genvalidity-sydtest-persistent
  - genvalidity-text
  - genvalidity-time
  - genvalidity-unordered-containers
  - genvalidity-uuid
  - genvalidity-vector

ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef

system-ghc: true
nix:
  enable: false
with-hpack: hpack
