resolver: lts-21.22
packages:
- bevel-api
- bevel-api-gen
- bevel-api-server
- bevel-api-server-data
- bevel-api-server-data-gen
- bevel-api-server-gen
- bevel-cli
- bevel-client
- bevel-client-data
- bevel-client-data-gen
- bevel-data
- bevel-data-gen
extra-deps:
- github: NorfairKing/servant
  commit: 552da96ff9a6d81a8553c6429843178d78356054
  subdirs:
  - servant 
  - servant-auth/servant-auth
  - servant-auth/servant-auth-client
  - servant-auth/servant-auth-server
  - servant-client
  - servant-client-core 
  - servant-server
- github: NorfairKing/autodocodec
  commit: fa4d53e6c7694427c9d777b883fc446c4f3651b0
  subdirs:
  - autodocodec
  - autodocodec-schema
  - autodocodec-yaml
- github: NorfairKing/safe-coloured-text
  commit: f18578151d579c495eda46b8eeafcddb69adea07
  subdirs:
  - safe-coloured-text
  - safe-coloured-text-layout
  - safe-coloured-text-terminfo
- github: NorfairKing/sydtest
  commit: dd1c2b9b39d0995c8581524e8b42b8ca1d0c427a
  subdirs:
  - sydtest
  - sydtest-aeson
  - sydtest-discover
  - sydtest-hspec
  - sydtest-persistent
  - sydtest-persistent-sqlite
  - sydtest-process
  - sydtest-servant
  - sydtest-typed-process
  - sydtest-wai
  - sydtest-yesod
- github: NorfairKing/appendful
  commit: 9100ac7fb88e8bb0357e6c648d1b5b404efcd4f8
  subdirs:
  - appendful
  - appendful-persistent
  - genvalidity-appendful
- github: NorfairKing/validity
  commit: a251897dc1eb7e851fd4d3dbc6fa976d22388f27
  subdirs:
  - validity
  - validity-aeson
  - validity-bytestring
  - validity-containers
  - validity-path
  - validity-persistent
  - validity-primitive
  - validity-scientific
  - validity-text
  - validity-time
  - validity-unordered-containers
  - validity-uuid
  - validity-vector
  - genvalidity
  - genvalidity-aeson
  - genvalidity-bytestring
  - genvalidity-containers
  - genvalidity-criterion
  - genvalidity-hspec
  - genvalidity-hspec-aeson
  - genvalidity-hspec-binary
  - genvalidity-hspec-cereal
  - genvalidity-hspec-hashable
  - genvalidity-hspec-optics
  - genvalidity-hspec-persistent
  - genvalidity-path
  - genvalidity-persistent
  - genvalidity-property
  - genvalidity-scientific
  - genvalidity-sydtest
  - genvalidity-sydtest-aeson
  - genvalidity-sydtest-hashable
  - genvalidity-sydtest-lens
  - genvalidity-sydtest-persistent
  - genvalidity-text
  - genvalidity-time
  - genvalidity-unordered-containers
  - genvalidity-uuid
  - genvalidity-vector

ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef

system-ghc: true
nix:
  enable: false
with-hpack: hpack
