resolver: lts-23.19
packages:
- bevel-api
- bevel-api-gen
- bevel-api-server
- bevel-api-server-data
- bevel-api-server-data-gen
- bevel-api-server-gen
- bevel-cli
- bevel-client
- bevel-client-data
- bevel-client-data-gen
- bevel-data
- bevel-data-gen


ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef

extra-deps:
- looper-0.3.0.2@sha256:f880aead01250795cbcb8b5d0b32902ac2b2fff76d265da1977e8c35d8580396,1379
- opt-env-conf-0.9.0.0@sha256:21d89d24f0f83f6e01ddcbfa688d228e9ddb8489d69a11af1945050605851a2c,1709
- opt-env-conf-test-0.0.0.2@sha256:a4f968e4223977f445e84e515e361e0217a25187fe55aee4f1cd5b911637101d,17412
- github: NorfairKing/necrork
  commit: 87cd9f2a4ebfffdcf393f87de6851f7b124184c5
  subdirs:
    - necrork

system-ghc: true
nix:
  enable: false
with-hpack: hpack
