name: bevel-data-gen
version: 0.0.0.0
github: "NorfairKing/bevel"
license: AllRightsReserved
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - genvalidity
    - genvalidity-path
    - genvalidity-text
    - bevel-data

tests:
  bevel-data-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - sydtest
    - bevel-data
    - bevel-data-gen
