[target.x86_64-unknown-linux-musl]
rustflags = [
  "-C", "link-arg=-static",
  "-C", "target-feature=+crt-static",
  "-C", "relocation-model=static",
  "-C", "strip=symbols",
]

[profile.release]
lto = true # Link Time Optimization (LTO)
