name: bevel-cli
version: 0.0.0.0
github: "NorfairKing/bevel"
license: AllRightsReserved
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson-pretty
  - appendful-persistent
  - async
  - autodocodec
  - autodocodec-yaml
  - bevel-api
  - bevel-api-server-data
  - bevel-client
  - bevel-client-data
  - bevel-data
  - brick
  - bytestring
  - conduit
  - containers
  - cookie
  - cursor
  - cursor-brick
  - envparse
  - esqueleto
  - filelock
  - filepath
  - hostname
  - http-client
  - http-client-tls
  - monad-logger
  - mtl
  - optparse-applicative
  - path
  - path-io
  - persistent
  - persistent-pagination
  - persistent-sqlite
  - servant-client
  - text
  - time
  - unix
  - unliftio
  - vector
  - vty
  - witherable
  - yaml

executables:
  bevel:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bevel-cli

benchmarks:
  bevel-cli-bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - bevel-cli
    - bevel-client-data
    - bevel-client-data-gen
    - bevel-data
    - conduit
    - criterion
    - genvalidity
    - monad-logger
    - path
    - path-io
    - persistent
    - persistent-sqlite
    - text
    - time

tests:
  bevel-cli-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - async
    - bevel-api
    - bevel-api-server-data
    - bevel-api-server-gen
    - bevel-cli
    - bevel-client-data
    - bevel-client-data-gen
    - genvalidity-sydtest
    - genvalidity-text
    - genvalidity-time
    - monad-logger
    - path
    - path-io
    - persistent-sqlite
    - servant-client
    - sydtest
    - text
    - typed-process
