name: bevel-data
version: 0.0.0.0
github: "NorfairKing/bevel"
license: AllRightsReserved
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "Copyright (c) 2020-2022 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - autodocodec
    - base16
    - bytestring
    - containers
    - cryptohash-sha256
    - directory
    - filepath
    - path
    - path
    - path-io
    - persistent
    - random-shuffle
    - safe
    - text
    - time
    - validity
    - validity-bytestring
    - validity-containers
    - validity-path
    - validity-text
    - validity-time
    - yaml
    - yamlparse-applicative
