name:                bevel-api-server-data
version:             0.0.0.0
github:              "NorfairKing/bevel"
license:             AllRightsReserved
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright (c) 2020-2022 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - appendful
    - appendful-persistent
    - autodocodec
    - bevel-data
    - password
    - password-instances
    - path
    - persistent
    - persistent-sqlite
    - persistent-template
    - text
    - time
    - validity
    - validity-persistent
    - validity-text
