name:                bevel-client
version:             0.0.0.0
github:              "NorfairKing/bevel"
license:             AllRightsReserved
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright (c) 2020-2022 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - servant
    - servant-auth
    - servant-auth-client
    - servant-client
    - servant-client-core
    - text
    - validity
    - validity-text
    - bevel-api
