name: bevel-client-data-gen
version: 0.0.0.0
github: "NorfairKing/bevel"
license: AllRightsReserved
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - QuickCheck
    - bytestring
    - bevel-client-data
    - bevel-data-gen
    - genvalidity
    - genvalidity-persistent
    - genvalidity-text
    - password
    - text

tests:
  bevel-client-data-test:
    main: Spec.hs
    build-tools: sydtest-discover
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - genvalidity-sydtest
    - sydtest
    - bevel-client-data
    - bevel-client-data-gen
