[package]
name = "bevel-select"
version = "0.0.0"
edition = "2021"

[dependencies]
tui = "*"
crossterm = "*"
sqlite = "*"
ordered-float = "*"
whoami = "*"
fallible = "*"
fuzzy-matcher = "*"
xdg = "*"
