name: bevel-api-server
version: 0.0.0.0
github: "NorfairKing/bevel"
license: AllRightsReserved
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  build-tools: autoexporter
  dependencies:
    - appendful-persistent
    - autodocodec
    - autodocodec-yaml
    - bevel-api
    - bevel-api-server-data
    - bevel-data
    - envparse
    - jose
    - monad-logger
    - monad-logger
    - mtl
    - opt-env-conf
    - optparse-applicative
    - password
    - path
    - path-io
    - persistent
    - persistent-sqlite
    - prometheus
    - prometheus-wai
    - servant-auth-server
    - servant-server
    - text
    - wai
    - wai-extra
    - warp
    - yaml

executables:
  bevel-api-server:
    main: Main.hs
    source-dirs: app/
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -with-rtsopts=-Iw60 # Only idle-gc once per minute
    - -with-rtsopts=--nonmoving-gc # GC with more consistent latency
    dependencies:
      - bevel-api-server
