name:                bevel-api
version:             0.0.0.0
github:              "NorfairKing/bevel-api-cli-login"
license:             AllRightsReserved
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright (c) 2020-2022 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - appendful
    - bevel-api-server-data
    - bevel-client-data
    - bevel-data
    - jose
    - persistent
    - servant
    - servant-auth
    - servant-auth-server
    - text
    - validity
    - validity-text
